很多有返回值的内置函数是不能被延迟调用的

-   自定义函数的调用的返回结果都可以被舍弃
-   大多数内置函数（除了`copy`和`recover`）的调用的返回结果都不可以舍弃

```
5| func main() {
6| 	s := []string{"a", "b", "c", "d"}
7| 	defer fmt.Println(s) // [a x y d]
8| 	// defer append(s[:1], "x", "y") // 编译错误
9| 	defer func() {
10| 	_ = append(s[:1], "x", "y")
11| }()
12| }
```



延迟调用的函数值的估值时刻

-   一个被延迟调用的函数值是在其调用被推入延迟调用队列之前被估值的
-   一个被延迟调用的函数值可能是一个`nil`函数值。这种情形将导致一个恐慌。 对于这种情形，恐慌产生在此延迟调用被执行而不是被推入延迟调用队列的时候



Pp. 307-311